#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES=0 python main.py \
    --output_dir ./experiment_SRGAN_VGG54/ \
    --summary_dir ./experiment_SRGAN_VGG54/log/ \
    --mode train \
    --is_training True \
    --task SRGAN \
    --batch_size 16 \
    --flip True \
    --random_crop True \
    --crop_size 24 \
    --input_dir_LR /home/dl2/Desktop/workspace/khj/SDC/SRGAN-tensorflow-master/data/train/SH_trainSet/ver7_shTrainSet_train/Review_120_LR \
    --input_dir_HR /home/dl2/Desktop/workspace/khj/SDC/SRGAN-tensorflow-master/data/train/SH_trainSet/ver7_shTrainSet_train/Review_480_HR \
    --num_resblock 16 \
    --perceptual_mode VGG54 \
    --name_queue_capacity 4096 \
    --image_queue_capacity 4096 \
    --ratio 0.001 \
    --learning_rate 0.0001 \
    --decay_step 100000 \
    --decay_rate 0.1 \
    --stair True \
    --beta 0.9 \
    --max_iter 200000 \
    --save_freq 5000 \
    --queue_thread 10 \
    --vgg_scaling 0.0061 \
    --pre_trained_model True \
    --checkpoint /home/dl2/Desktop/workspace/khj/SDC/SRGAN-tensorflow-master/experiment_SRGAN_VGG54/ver7_shTrainSet_train/model-12000_29.25PSNR